namespace Supabase.Gotrue.Mfa
{
    /// <summary>
    /// Parameters for the MfaChallengeAndVerify method. This is used to challenge a factor and verify the code provided by the user.
    /// </summary>
    public class MfaChallengeAndVerifyParams
    {
        /// <summary>
        /// The ID of the factor to challenge and verify. This is the same as the Id property of the Factor class.
        /// </summary>
        public string FactorId { get; set; } = string.Empty;

        /// <summary>
        /// The code provided by the user to verify the challenged factor. This is typically a 6-digit code generated by an authenticator app or sent via SMS.
        /// </summary>
        public string Code { get; set; } = string.Empty;
    }
}
